### ISSUE TITLE
vertical-align also works on table cells

### ISSUE THREAD

**Issue by tigt** [captainbrosset/inactive-css#4]
[`rules` lines 64–65](https://github.com/captainbrosset/inactive-css/blob/master/rules#L64-L65):

```
vertical-align
  = !inlineLevel && !firstLetterPseudo && !firstLinePseudo
```

There’s a demo of the effect on `display: table-cell` in [the `vertical-align` MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align).

Presumably this is as straightforward as adding `&&!tableCell`?

**Comment by captainbrosset** [comment]
Thanks for reporting, indeed, adding `&& !tableCell` seems like the right thing to do. I'll do the change.
